### ISSUE TITLE
[Reborn] 7.0 Release - Webpack 5 and Rspack support

### ISSUE THREAD

**Issue by xc2** [xc2/svg-sprite-loader#1]
## Goals

- Loader/Plugin options should be compatible with 6.x.
- Should work well with webpack 5 and rspack
- Should work without @types/svg-sprite-loader
- A new package name like svg-sprite-loader-reborn

## TODO

- [ ] fix webpack 5 support for extract mode with mini-css-extract-plugin and html-loader
- [ ] fix rspack support
- [ ] drop webpack 1-4 support and cleanup related code
- [ ] bump or remove all obsolete deps
- [ ] type all source code with jsdoc and generate d.ts via tsc
- [ ] update document
